site_name: My Safe Haven
docs_dir: docs
site_dir: site

nav:
  - Inicio: index.md
  - Despliegue: despliegue.md
  - Arquitectura: arquitectura.md
  - Inicio de sesión y pantalla principal: app1.md
  - Mis Havens: app2.md
  - Havens cercanos y perfil: app3.md

theme:
  name: mkdocs
