FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar la app
COPY my_safe_haven_back ./my_safe_haven_back

WORKDIR /app/my_safe_haven_back

# Crear la carpeta uploads dentro del contenedor
RUN mkdir -p uploads

EXPOSE 5050

CMD ["python", "app.py"]
