CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    mail VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    profile_image_path VARCHAR(500),
    password_hash VARCHAR(255) NOT NULL,
    pro BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS havens (
    haven_id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    radius DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS haven_posts (
    post_id SERIAL PRIMARY KEY,
    haven_id INTEGER NOT NULL REFERENCES havens(haven_id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS chat_messages (
    message_id SERIAL PRIMARY KEY,
    haven_id INTEGER NOT NULL REFERENCES havens(haven_id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT NOW()
);
